name: Continuous Integration

on: 
  pull_request:
  push:
    branches: 
      - main

jobs:
  test-and-lint:
    name: Run tests and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.17.1
      - run: pnpm install -r --frozen-lockfile
      - run: pnpm run -r check:lint
      - run: pnpm run -r check:typescript
      - run: pnpm run -r check:test
